name: "Python Smoke Tests"

on:
  pull_request:
  push:
  workflow_call:
  workflow_dispatch:

jobs:
  smoke_job:
    name: Smoke Actions Job
    runs-on: ubuntu-latest

    steps:
      - run:
          sh ./run_tests.sh
