name: "Python Smoke Tests"

on:
  pull_request:
  push:
  workflow_call:
  workflow_dispatch:

jobs:
  smoke_job:
    name: Smoke Actions Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install python requirements
        run: pip install -r ./python/requirements.txt

      # - name: Install Firefox
        # run: sudo apt install firefox

      # - name: Install geckodriver
        # run: sudo apt-get install firefox-geckodriver

      - name: Run tests
        run:
          sh ./run_tests.sh
